### ISSUE TITLE
Rewrite it in Rust

### ISSUE THREAD

**Issue by Tairesh** [Zuzuk-null/calculator#1]
Rust is modern popular open source language and it's as fast as C++, so you definetly need to rewrite this project completely in Rust

**Comment by Zuzuk-null** [comment]
> Rust is modern popular open source language and it's as fast as C++, so you definetly need to rewrite this project completely in Rust

Rust is still a fairly young language with an unformed ecosystem.  Also, note that this language is not as popular as, for example, C ++ or C, therefore, it will be rather difficult to find Rust programmers. Therefore, it don't need to rewrite it in Rust.

**Comment by Tairesh** [comment]
>  Rust is still a fairly young language with an unformed ecosystem. Also, note that this language is not as popular as, for example, C ++ or C, therefore, it will be rather difficult to find Rust programmers. 

So you prefer Haskell for this very reasons

**Comment by Zuzuk-null** [comment]
> So you prefer Haskell for this very reasons

This is exactly so
